--- # install httpd server using ansible
- hosts: 127.0.0.1
  #user: ansadmin
  become: yes
  connection: ssh
  gather_facts: yes
  
  vars:
    user_name: devops
    group: office
    passphrase: Riju@8100006942
    user_email: mail2susantasadhukhan@gmail.com

  tasks:
       - name: create a password for user {{user_name}}
         shell: python3 -c 'import crypt,getpass; print(crypt.crypt(getpass.getpass(), crypt.mksalt(crypt.METHOD_SHA512)))'
         register: password
           

     
